import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
const base='http://127.0.0.1:8790';let checks=0,admin;
async function call(route,method='GET',body,device,expected=200,asAdmin=false){const response=await fetch(base+route,{method,headers:{...(asAdmin?{Authorization:'Bearer '+admin}:device?{'X-Device-Token':device}:{}),...(body?{'Content-Type':body instanceof Uint8Array?'image/png':'application/json'}:{})},...(body?{body:body instanceof Uint8Array?body:JSON.stringify(body)}:{})});const data=await response.json();assert.equal(response.status,expected,route+': '+JSON.stringify(data));checks++;return data.data;}
admin=(await call('/api/auth/login','POST',{username:'integration-admin',password:'Integration-password-2026'})).token;
const suffix=Date.now(),password='Reader-password-2026';
const group=await call('/api/access-groups','POST',{name:'设备测试组-'+suffix},null,201,true);
const account=await call('/api/reader-accounts','POST',{username:'reader-'+suffix,password,group_id:group.id},null,201,true);
let token=randomBytes(32).toString('hex'),id=randomUUID();const credentials={username:account.username,password,display_name:'三楼走廊显示屏',device_id:id,device_token:token};
await call('/api/reader-accounts','POST',{username:'bypass',password,group_id:group.id},null,401);
await call('/api/items', 'GET',undefined,null,401);await call('/api/items/cache-status?ids=1','GET',undefined,null,401);
await call('/api/device/apply','POST',{...credentials,password:'Wrong-password-2026'},null,401);
const pending=await call('/api/device/apply','POST',credentials,null,201);assert.equal(pending.status,'pending');assert.equal(pending.group_id,group.id);checks++;
await call('/api/items','GET',undefined,token,403);await call('/api/devices','GET',undefined,token,401);
await call('/api/devices/'+id,'PATCH',{status:'approved'},token,401);
await call('/api/devices/'+id,'PATCH',{status:'approved'},null,200,true);
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=','base64');
const image=await call('/api/images','POST',png,null,201,true);
await call('/api/images/'+image.id,'GET',undefined,null,401);
let imageResponse=await fetch(base+'/api/images/'+image.id,{headers:{'X-Device-Token':token}});assert.equal(imageResponse.status,404);checks++;
const item=await call('/api/items','POST',{title:'授权设备测试',status:'found',image_id:image.id},null,201,true);
const found=await call('/api/items','GET',undefined,token);assert.ok(found.some(row=>row.id===item.id));assert.ok(found.every(row=>row.status==='found'));checks++;
await call('/api/items?status=claimed','GET',undefined,token,403);
imageResponse=await fetch(base+'/api/images/'+image.id,{headers:{'X-Device-Token':token}});assert.equal(imageResponse.status,200);assert.equal(imageResponse.headers.get('cache-control'),'private, no-store');checks++;
await call('/api/items/'+item.id,'PUT',{status:'claimed'},token,401);
await call('/api/items/'+item.id,'PUT',{status:'claimed'},null,200,true);
await call('/api/items/'+item.id,'GET',undefined,token,404);
imageResponse=await fetch(base+'/api/images/'+image.id,{headers:{'X-Device-Token':token}});assert.equal(imageResponse.status,404);checks++;
const states=await call('/api/items/cache-status?ids='+item.id,'GET',undefined,token);assert.equal(states[0].status,'claimed');assert.ok(!('title' in states[0]));checks++;
await call('/api/device/apply','POST',{...credentials,device_token:randomBytes(32).toString('hex')},null,409);
await call('/api/reader-accounts/'+account.id,'PATCH',{enabled:false},null,200,true);await call('/api/items','GET',undefined,token,403);
await call('/api/reader-accounts/'+account.id,'PATCH',{enabled:true},null,200,true);await call('/api/items','GET',undefined,token);
await call('/api/access-groups/'+group.id,'PATCH',{enabled:false},null,200,true);await call('/api/items','GET',undefined,token,403);
await call('/api/access-groups/'+group.id,'PATCH',{enabled:true},null,200,true);
await call('/api/devices/'+id,'PATCH',{status:'revoked'},null,200,true);await call('/api/items','GET',undefined,token,403);
await call('/api/device/apply','POST',credentials,null,429);await call('/api/devices/'+id,'PATCH',{status:'rejected'},null,200,true);await call('/api/items','GET',undefined,token,403);
await call('/api/reader-accounts/'+account.id,'PATCH',{password:'New-reader-password-2026'},null,200,true);await call('/api/device/apply','POST',credentials,null,401);
id=randomUUID();token=randomBytes(32).toString('hex');credentials.device_id=id;credentials.device_token=token;
await call('/api/device/apply','POST',{...credentials,password:'New-reader-password-2026'},null,201);await call('/api/devices/'+id,'PATCH',{status:'approved'},null,200,true);
const devices=await call('/api/devices','GET',undefined,null,200,true);assert.ok(!JSON.stringify(devices).includes(token));assert.ok(!JSON.stringify(devices).includes('token_hash'));checks++;
const logs=await call('/api/logs?action=device.review','GET',undefined,null,200,true);assert.ok(logs.some(log=>log.target==='devices/'+id));assert.ok(!JSON.stringify(logs).includes(password));checks++;
await call('/api/items/'+item.id,'DELETE',undefined,null,200,true);await call('/api/images/'+image.id,'DELETE',undefined,null,200,true);await call('/api/reader-accounts/'+account.id,'PATCH',{enabled:false},null,200,true);await call('/api/access-groups/'+group.id,'PATCH',{enabled:false},null,200,true);
console.log(checks+' 项设备审批 / 组和账号授权 / 图片限制 / 密码重设 / 日志检查通过');
