import assert from 'node:assert/strict';
const origin = process.env.LAF_TEST_URL ?? 'http://127.0.0.1:8790';
if (!['localhost', '127.0.0.1', '[::1]'].includes(new URL(origin).hostname)) throw new Error('集成测试只允许本地服务器');
let checks = 0;
async function call(route, method = 'GET', body, token, expected = 200, headers = {}) {
  const response = await fetch(`${origin}${route}`, { method, headers: { ...(body && !(body instanceof Uint8Array) ? { 'Content-Type': 'application/json' } : {}), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...headers }, ...(body ? { body: body instanceof Uint8Array ? body : JSON.stringify(body) } : {}) });
  const data = await response.json();
  assert.equal(response.status, expected, `${method} ${route}: ${JSON.stringify(data)}`); checks++;
  return data.data;
}
const suffix = Date.now();
const credentials = { username: 'integration-admin', password: 'Integration-password-2026' };
const bootstrap = await fetch(`${origin}/api/auth/bootstrap`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Bootstrap-Key': process.env.LAF_TEST_KEY ?? 'local-integration-only' }, body: JSON.stringify(credentials) });
assert.ok([201, 409].includes(bootstrap.status), `bootstrap ${bootstrap.status}`); checks++;
const admin = (await call('/api/auth/login', 'POST', credentials)).token;
await call('/api/auth/bootstrap', 'POST', { username: 'another-admin', password: 'Another-password-2026' }, null, 403);
await call('/api/items', 'POST', { title: '禁止匿名写入', status: 'found' }, null, 401);
await call('/api/users', 'GET', undefined, null, 401);
await call('/api/users', 'POST', { username: 'bypass', role: 'admin' }, admin, 405);
const applicant = { username: `editor-${suffix}`, password: 'Editor-password-2026' };
await call('/api/auth/register', 'POST', { ...applicant, role: 'admin' }, null, 400);
const editorUser = await call('/api/auth/register', 'POST', applicant, null, 201);
assert.equal(editorUser.approval_status, 'pending'); assert.equal(editorUser.role, 'editor'); assert.ok(!('password_hash' in editorUser)); checks++;
await call('/api/auth/login', 'POST', applicant, null, 403);
await call(`/api/users/${editorUser.id}`, 'PATCH', { approval_status: 'approved' }, admin);
let editor = (await call('/api/auth/login', 'POST', applicant)).token;
await call('/api/users', 'GET', undefined, editor, 403);
await call('/api/logs', 'GET', undefined, editor, 403);
await call('/api/images', 'POST', new TextEncoder().encode('<svg/>'), editor, 415);
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aD1sAAAAASUVORK5CYII=', 'base64');
const image = await call('/api/images', 'POST', png, editor, 201);
const downloaded = await fetch(`${origin}/api/images/${image.id}`,{headers:{Authorization:`Bearer ${admin}`}});
assert.equal(downloaded.headers.get('content-type'), 'image/png'); assert.deepEqual(Buffer.from(await downloaded.arrayBuffer()), png); checks++;
const item = await call('/api/items', 'POST', { title: '测试保温杯', description: '蓝色杯身', status: 'found', image_id: image.id, floor: '二层' }, editor, 201);
assert.deepEqual(Object.keys(item).sort(), ['id','title','description','floor','created_at','status','image_id'].sort()); assert.equal(item.image_id, image.id); assert.ok(item.created_at); checks++;
await call(`/api/images/${image.id}`, 'DELETE', undefined, editor, 409);
assert.equal((await call(`/api/items/${item.id}`,'GET',undefined,admin)).description, '蓝色杯身'); checks++;
await call(`/api/items/${item.id}`, 'PUT', { status: 'claimed' }, editor);
assert.ok(!(await call('/api/items?status=found','GET',undefined,admin)).some(record => record.id === item.id));
const state = (await call(`/api/items/cache-status?ids=${item.id}`,'GET',undefined,admin))[0];
assert.equal(state.status, 'claimed'); assert.ok(state.claimed_at); checks++;
await call('/api/items/cache-status?ids=bad', 'GET', undefined, admin, 400);
await call(`/api/items/${item.id}`, 'PUT', { created_by: 1 }, editor, 400);
await call(`/api/items/${item.id}`, 'PUT', { image_id: '33333333-3333-3333-3333-333333333333' }, editor, 400);
await call(`/api/users/${editorUser.id}`, 'PATCH', { approval_status: 'disabled' }, admin);
await call(`/api/items/${item.id}`, 'PUT', { status: 'found' }, editor, 401);
await call('/api/auth/login', 'POST', applicant, null, 403);
await call(`/api/users/${editorUser.id}`, 'PATCH', { approval_status: 'approved' }, admin);
editor = (await call('/api/auth/login', 'POST', applicant)).token;
await call('/api/auth/password', 'POST', { oldPassword: applicant.password, password: 'New-editor-password-2026' }, editor);
await call('/api/auth/me', 'GET', undefined, editor, 401);
editor = (await call('/api/auth/login', 'POST', { ...applicant, password: 'New-editor-password-2026' })).token;
await call(`/api/items/${item.id}`, 'DELETE', undefined, editor);
await call(`/api/items/${item.id}`, 'GET', undefined, admin, 404);
await call(`/api/images/${image.id}`, 'DELETE', undefined, editor);
await call(`/api/images/${image.id}`, 'GET', undefined, admin, 404);
const logs = await call('/api/logs', 'GET', undefined, admin);
assert.ok(logs.some(log => log.action === 'item.create' && log.target === `items/${item.id}`));
assert.ok(logs.some(log => log.action === 'item.delete' && log.target === `items/${item.id}`)); checks++;
await call('/api/auth/logout', 'POST', undefined, editor);
await call('/api/auth/me', 'GET', undefined, editor, 401);
await call(`/api/users/${editorUser.id}`, 'PATCH', { approval_status: 'rejected' }, admin);
console.log(`${checks} 项真实 HTTP / D1 / R2 / 权限检查通过`);
