import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new DatabaseSync(':memory:');
db.exec('PRAGMA foreign_keys=ON');
for(const name of ['0001_initial.sql','0002_auth_images.sql'])db.exec(readFileSync(new URL(`../migrations/${name}`,import.meta.url),'utf8'));
db.exec(`INSERT INTO users (username,password_hash,role) VALUES ('fixture','test-only','editor');
INSERT INTO images (id,object_key,content_type,size,uploaded_by) VALUES ('11111111-1111-1111-1111-111111111111','fixture-image','image/png',1,1);
INSERT INTO items (title,description,category,location,status,image_id,created_at,updated_at) VALUES ('旧物品','保留描述','旧类别','三层','claimed','11111111-1111-1111-1111-111111111111','2026-09-01 00:00:00','2026-09-02 00:00:00');
INSERT INTO items (title,status) VALUES ('已删除序号','found'); DELETE FROM items WHERE id=2;`);
db.exec(readFileSync(new URL('../migrations/0003_item_fields.sql',import.meta.url),'utf8'));
assert.deepEqual(db.prepare('PRAGMA table_info(items)').all().map(row=>row.name),['id','title','description','floor','created_at','status','image_id']);
const row=db.prepare('SELECT * FROM items WHERE id=1').get();assert.equal(row.floor,'三层');assert.equal(row.description,'保留描述');assert.equal(row.created_at,'2026-09-01 00:00:00');assert.ok(row.image_id);
assert.equal(db.prepare('SELECT claimed_at FROM item_claims WHERE item_id=1').get().claimed_at,'2026-09-02 00:00:00');
assert.equal(db.prepare('SELECT category FROM _legacy_items_v03 WHERE id=1').get().category,'旧类别');
assert.equal(db.prepare("INSERT INTO items (title,status) VALUES ('新物品','found') RETURNING id").get().id,3);
db.exec("UPDATE items SET status='found' WHERE id=1");assert.equal(db.prepare('SELECT COUNT(*) AS count FROM item_claims WHERE item_id=1').get().count,0);
db.exec("UPDATE items SET status='claimed' WHERE id=1");assert.ok(db.prepare('SELECT claimed_at FROM item_claims WHERE item_id=1').get().claimed_at);
db.close();console.log('旧数据迁移验证通过：七字段、楼层映射、时间与图片保留、序号不重用、认领生命周期、旧字段恢复存档');
