import assert from 'node:assert/strict';
const base=process.env.LAF_TEST_URL??'http://127.0.0.1:8790';
if(!['localhost','127.0.0.1','[::1]'].includes(new URL(base).hostname))throw Error('Tests require a local server');
let checks=0;
async function call(route,method='GET',body,cookie,expected=200,origin=base){
 const response=await fetch(base+route,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(body?{'Content-Type':body instanceof Uint8Array?'application/octet-stream':'application/json'}:{}),...(method!=='GET'?{Origin:origin}:{})},...(body?{body:body instanceof Uint8Array?body:JSON.stringify(body)}:{})});
 const payload=await response.json();assert.equal(response.status,expected,`${route}: ${JSON.stringify(payload)}`);checks++;
 return {data:payload.data,cookie:response.headers.get('set-cookie')?.split(';')[0],headers:response.headers};
}
const page=await fetch(base+'/editor/');assert.equal(page.status,200);assert.ok((await page.text()).includes('网页编辑工作台'));assert.ok(page.headers.get('content-security-policy').includes("frame-ancestors 'none'"));checks++;
const script=await fetch(base+'/editor/app.js');assert.ok(!(await script.text()).includes('window.laf'));checks++;
const adminLogin=await call('/api/auth/login','POST',{username:'integration-admin',password:'Integration-password-2026'});
assert.ok(adminLogin.headers.get('set-cookie').includes('HttpOnly'));assert.ok(adminLogin.headers.get('set-cookie').includes('SameSite=Strict'));checks++;
const admin=adminLogin.cookie;
const credentials={username:`web-editor-${Date.now()}`,password:'Web-password-2026'};
const registered=(await call('/api/auth/register','POST',credentials,undefined,201)).data;
await call(`/api/users/${registered.id}`,'PATCH',{approval_status:'approved'},admin);
let editor=(await call('/api/auth/login','POST',credentials)).cookie;
await call('/api/logs','GET',undefined,editor,403);
await call(`/api/users/${registered.id}`,'PATCH',{can_edit:false},editor,403);
await call('/api/items','POST',{title:'CSRF',status:'found'},editor,403,'https://untrusted.example');
const item=(await call('/api/items','POST',{title:'网页测试记录',description:'修改前',floor:'二层',status:'found'},editor,201)).data;
await call(`/api/items/${item.id}`,'PUT',{description:'修改后',status:'claimed'},editor);
const logs=(await call(`/api/logs?user_id=${registered.id}&action=item.update`,'GET',undefined,admin)).data;
assert.equal(logs[0].username,credentials.username);const details=JSON.parse(logs[0].details);assert.equal(details.before.description,'修改前');assert.equal(details.after.description,'修改后');assert.equal(details.after.status,'claimed');checks++;
await call(`/api/users/${registered.id}`,'PATCH',{can_edit:false},admin);
await call('/api/auth/me','GET',undefined,editor,401);
const revoked=await call('/api/auth/login','POST',credentials);editor=revoked.cookie;assert.equal(revoked.data.user.can_edit,0);checks++;
await call(`/api/items/${item.id}`,'PUT',{title:'禁止修改'},editor,403);
await call('/api/items','POST',{title:'禁止发布',status:'found'},editor,403);
await call(`/api/items/${item.id}`,'DELETE',undefined,editor,403);
await call('/api/images','POST',new Uint8Array([137,80,78,71,13,10,26,10]),editor,403);
await call('/api/items','GET',undefined,editor);
await call(`/api/users/${registered.id}`,'PATCH',{can_edit:true},admin);
editor=(await call('/api/auth/login','POST',credentials)).cookie;
await call(`/api/items/${item.id}`,'DELETE',undefined,editor);
const permissions=(await call('/api/logs?action=user.permission','GET',undefined,admin)).data;assert.ok(permissions.some(log=>log.target===`users/${registered.id}`));checks++;
const passwordLogs=(await call(`/api/logs?user_id=${registered.id}`,'GET',undefined,admin)).data;assert.ok(!JSON.stringify(passwordLogs).includes(credentials.password));checks++;
await call('/api/auth/logout','POST',undefined,editor);await call('/api/auth/me','GET',undefined,editor,401);
await call(`/api/users/${registered.id}`,'PATCH',{approval_status:'disabled'},admin);
console.log(`${checks} 项网页会话 / CSRF / 编辑权限 / 审计日志检查通过`);
