const { app, BrowserWindow, dialog, ipcMain } = require('electron');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const storage = require('../src/storage.cjs');
const { trayIcon } = require('../src/tray-icon.cjs');
const role = process.argv[2];
if (!['viewer', 'editor'].includes(role)) throw new Error('需要独立客户端类型');
const output = path.resolve(__dirname, `../test-output/${role}`);
process.env.LAF_TEST_PROFILE = path.join(output, `profile-${Date.now()}`);
app.setPath('userData', process.env.LAF_TEST_PROFILE);
app.setPath('sessionData', process.env.LAF_TEST_PROFILE);
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
let itemId, secondId, imageId, replacementImage, adminToken, applicantId;
const origin = 'http://127.0.0.1:8790';
const registeredChannels = [];
const originalHandle = ipcMain.handle.bind(ipcMain);
ipcMain.handle = (channel, handler) => { registeredChannels.push(channel); return originalHandle(channel, handler); };
async function http(route, method, body) {
  const response = await fetch(origin + route, { method, headers: { ...(adminToken ? { Authorization: `Bearer ${adminToken}` } : {}), ...(Buffer.isBuffer(body) ? {} : { 'Content-Type': 'application/json' }) }, ...(body ? { body: Buffer.isBuffer(body) ? body : JSON.stringify(body) } : {}) });
  const json = await response.json(); if (!json.success) throw new Error(json.error); return json.data;
}
async function waitUntil(fn, label) { for (let i = 0; i < 150; i++) { if (await fn()) return; await delay(100); } throw new Error(`等待超时：${label}`); }
async function run() {
  await fs.mkdir(output, { recursive: true });
  await storage.writeJson(path.join(process.env.LAF_TEST_PROFILE, 'settings.json'), { ...storage.defaults, serverUrl: origin, showClaimed: true, closeToTray: role === 'viewer' });
  adminToken = (await http('/api/auth/login', 'POST', { username: 'integration-admin', password: 'Integration-password-2026' })).token;
  imageId = (await http('/api/images', 'POST', trayIcon())).id;
  itemId = (await http('/api/items', 'POST', { title: '蓝色保温杯', description: '在教学楼二层拾获。杯盖为深蓝色，请到值班室核对领取。', floor: '二层', status: 'found', image_id: imageId })).id;
  if (role === 'viewer') secondId = (await http('/api/items', 'POST', {title:'钥匙',floor:'三层',status:'found'})).id;
  // A legacy flag must not turn the standalone viewer into an editor.
  if (role === 'viewer') process.argv.push('--editor');
  require(path.resolve(__dirname, `../../laf-${role}/src/main.cjs`));
  await app.whenReady();
  await waitUntil(() => BrowserWindow.getAllWindows().length > 0, '独立 GUI 窗口');
  const win = BrowserWindow.getAllWindows()[0];
  const js = script => win.webContents.executeJavaScript(script);
  const checks = ['independent-window', 'isolated-profile', 'renderer-isolation'];
  const errors = [];
  win.webContents.on('console-message', (_, details) => { if (details.level === 'error') errors.push(details.message); });
  assert.equal(app.getPath('userData'), process.env.LAF_TEST_PROFILE);
  assert.equal(app.getName(), role === 'viewer' ? '失物招领只读客户端' : '失物招领编辑客户端');
  assert.equal(await js('typeof require'), 'undefined');
  async function capture(name) { await delay(400); const image = await win.capturePage(); await fs.writeFile(path.join(output, name), image.toPNG()); }
  if (role === 'viewer') {
    await waitUntil(() => js(`document.querySelector('[data-id="${itemId}"]')`), '只读记录列表');
    assert.equal(await js('document.querySelectorAll("#cards img").length'), 0);
    assert.equal(win.isResizable(), false);
    assert.equal(await js('document.documentElement.scrollWidth <= window.innerWidth'), true);
    const capabilities = await js('Object.keys(window.laf)');
    for (const forbidden of ['api', 'login', 'register', 'logout', 'uploadImage', 'openEditor', 'user']) assert.ok(!capabilities.includes(forbidden), `只读桥接包含 ${forbidden}`);
    for (const channel of ['api', 'auth:login', 'auth:register', 'image:upload', 'window:editor']) assert.ok(!registeredChannels.includes(channel), `只读进程注册了 ${channel}`);
    assert.equal(await js('Boolean(document.querySelector("#editor-open, #auth-form, #new-item"))'), false);
    await capture('viewer.png');
    await js(`document.querySelector('[data-id="${itemId}"]').click()`);
    await waitUntil(() => js('!document.querySelector("#details").hidden'), '只读侧边详情');
    assert.equal(win.getBounds().width, 800);
    assert.equal(await js('document.querySelectorAll(".record.active").length'), 1);
    await waitUntil(() => js('document.querySelector(".photo")?.naturalWidth > 0'), '完整图片');
    assert.equal(await js('Boolean(document.querySelector("#edit-item, #delete-item"))'), false);
    await capture('details.png');
    await js(`document.querySelector('[data-id="${secondId}"]').click()`);
    await waitUntil(() => js(`document.querySelector('.record.active')?.dataset.id === '${secondId}'`), '仅允许一条记录展开');
    assert.equal(await js('document.querySelectorAll(".record.active").length'), 1);
    assert.equal(await js('document.querySelectorAll("#details").length'), 1);
    await js('document.querySelector("#details-close").click()');
    await waitUntil(() => js('document.querySelector("#details").hidden'), '淡出收起');
    await js('document.querySelector("#settings-open").click()');
    assert.equal(await js('Boolean(document.querySelector("#settings-form"))'), true);
    const customRoot = path.join(output, 'custom-records');
    await fs.mkdir(customRoot, {recursive:true});
    dialog.showOpenDialog = async () => ({canceled:false,filePaths:[customRoot]});
    await js('document.querySelector("#choose-directory").click()');
    await waitUntil(() => js('Boolean(document.querySelector("#cacheDirectory").value)'), '选择保存目录');
    await capture('settings.png');
    await js('document.querySelector("#settings-form").requestSubmit()');
    await waitUntil(() => js('!document.querySelector("dialog").open'), '保存目录');
    assert.equal((await js('window.laf.settings()')).cacheDirectory, customRoot);
    await waitUntil(() => js('document.querySelector("#sync").textContent === "已同步"'), '目录切换后同步');
    await http(`/api/items/${secondId}`, 'PUT', {status:'claimed'});
    await js('document.querySelector("#refresh").click()');
    await waitUntil(() => js(`!document.querySelector('[data-id="${secondId}"]')`), '已认领记录立即隐藏');
    const savedLocal = await storage.readJson(path.join(storage.cacheDirectory(customRoot, origin),'records.json'));
    assert.equal(savedLocal.items.find(item=>item.id===secondId).status,'claimed');
    assert.ok(savedLocal.items.find(item=>item.id===secondId)._claimedAt);
    const dead = 'http://127.0.0.1:1';
    await fs.cp(storage.cacheDirectory(customRoot, origin), storage.cacheDirectory(customRoot, dead), { recursive: true });
    await js(`window.laf.saveSettings({ ...${JSON.stringify(storage.defaults)}, serverUrl:'${dead}', cacheDirectory:${JSON.stringify(customRoot)} })`);
    const offline = await js('window.laf.records(true)');
    assert.equal(offline.offline, true); assert.ok(offline.items.some(item => item.id === itemId));
    assert.ok(await js(`window.laf.image('${imageId}')`));
    checks.push('transparent-frameless', 'text-only-list', 'single-side-panel', 'custom-record-directory', 'read-only-bridge', 'no-write-ipc', 'legacy-flag-cannot-switch', 'records-gui', 'details-image', 'settings-gui', 'offline-cache', 'small-window-layout');
  } else {
    await waitUntil(() => js('Boolean(document.querySelector("#auth-form"))'), '编辑端登录 GUI');
    assert.ok(registeredChannels.includes('api'));
    assert.ok(!registeredChannels.includes('window:editor'));
    await capture('login.png');
    const applicant = `ui-editor-${Date.now()}`;
    await js('document.querySelector("#auth-register").click()');
    await js(`document.querySelector('#username').value='${applicant}'; document.querySelector('#password').value='UI-editor-password-2026'; document.querySelector('#confirm').value='UI-editor-password-2026'; document.querySelector('#auth-form').requestSubmit()`);
    await waitUntil(() => js(`document.querySelector('#auth-message')?.textContent.includes('申请已提交')`), '申请账号');
    applicantId = (await http('/api/users', 'GET')).find(user => user.username === applicant).id;
    await js('document.querySelector("#auth-login").click()');
    await js(`document.querySelector('#username').value='integration-admin'; document.querySelector('#password').value='Integration-password-2026'; document.querySelector('#auth-form').requestSubmit()`);
    await waitUntil(() => js('Boolean(document.querySelector("#nav-users"))'), '管理员登录');
    await waitUntil(() => js(`Boolean(document.querySelector('[data-id="${itemId}"]'))`), '编辑列表');
    await capture('editor.png');
    await js(`document.querySelector('[data-id="${itemId}"]').click()`);
    await waitUntil(() => js('Boolean(document.querySelector("#edit-item"))'), '记录编辑入口');
    await js('document.querySelector("#edit-item").click()');
    await waitUntil(() => js('Boolean(document.querySelector("#item-form"))'), '编辑表单 GUI');
    const uploadFile = path.join(output, 'sample-upload.png'); await fs.writeFile(uploadFile, trayIcon(true));
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [uploadFile] });
    await js('document.querySelector("#upload-image").click()');
    await waitUntil(() => js(`document.querySelector('#upload-name')?.textContent === 'sample-upload.png'`), '上传预览');
    await capture('form.png');
    await js(`document.querySelector('#title').value='蓝色保温杯（已确认）'; document.querySelector('#status').value='claimed'; document.querySelector('#item-form').requestSubmit()`);
    await waitUntil(() => js('!document.querySelector("dialog").open'), '保存编辑');
    const saved = await http(`/api/items/${itemId}`, 'GET'); assert.equal(saved.status, 'claimed'); replacementImage = saved.image_id; assert.notEqual(replacementImage, imageId);
    await js('document.querySelector("#nav-users").click()');
    await waitUntil(() => js('Boolean(document.querySelector(".table"))'), '账号审批 GUI');
    await js(`window.confirm=()=>true; document.querySelector('[data-user="${applicantId}"][data-status="approved"]').click()`);
    await waitUntil(() => js(`Boolean(document.querySelector('[data-user="${applicantId}"][data-status="disabled"]'))`), '批准账号');
    assert.equal((await http('/api/users', 'GET')).find(user => user.id === applicantId).approval_status, 'approved');
    assert.equal(await js('getComputedStyle(document.querySelector("#item-tools")).display'), 'none');
    await capture('users.png');
    await js('document.querySelector("#settings-open").click()');
    await waitUntil(() => js('Boolean(document.querySelector("#settings-form"))'), '编辑端设置 GUI');
    assert.equal(await js('Boolean(document.querySelector("[name=alwaysOnTop]"))'), false);
    assert.ok(await js(`document.querySelector('#settings-form').textContent.includes('开机自动启动编辑工作台')`));
    await js('document.querySelector("#refreshSeconds").value=90; document.querySelector("#settings-form").requestSubmit()');
    await waitUntil(() => js('!document.querySelector("dialog").open'), '编辑端保存设置');
    assert.equal((await js('window.laf.settings()')).refreshSeconds, 90);
    checks.push('login-gui', 'registration-gui', 'upload-preview-gui', 'edit-save', 'approval-gui', 'settings-save-gui', 'no-viewer-switch');
  }
  assert.equal(BrowserWindow.getAllWindows().length, 1);
  assert.deepEqual(errors, []);
  await fs.writeFile(path.join(output, 'result.json'), JSON.stringify({ success: true, role, time: new Date().toISOString(), checks }, null, 2));
  console.log(`${role} 独立 GUI 集成验证通过：${checks.join(', ')}`);
}
run().catch(async error => { console.error(error); process.exitCode = 1; await fs.mkdir(output, { recursive: true }); await fs.writeFile(path.join(output, 'result.json'), JSON.stringify({ success: false, role, error: error.stack })); }).finally(async () => {
  if (itemId) await http(`/api/items/${itemId}`, 'DELETE').catch(() => {});
  if (secondId) await http(`/api/items/${secondId}`, 'DELETE').catch(() => {});
  if (imageId) await http(`/api/images/${imageId}`, 'DELETE').catch(() => {});
  if (replacementImage) await http(`/api/images/${replacementImage}`, 'DELETE').catch(() => {});
  if (applicantId) await http(`/api/users/${applicantId}`, 'PATCH', { approval_status: 'disabled' }).catch(() => {});
  app.exit(process.exitCode || 0);
});
