const {app,BrowserWindow,dialog,safeStorage,screen}=require('electron');
const {createHash}=require('node:crypto');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const storage=require('../src/storage.cjs');
const output=path.resolve(__dirname,'../test-output/settings');
process.env.LAF_TEST_PROFILE=path.join(output,`profile-${Date.now()}`);
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitFor(fn){for(let i=0;i<150;i++){if(await fn())return;await delay(100);}throw Error('Settings GUI timeout');}
(async()=>{
 await fs.mkdir(output,{recursive:true});
 await storage.writeJson(path.join(process.env.LAF_TEST_PROFILE,'settings.json'),{...storage.defaults,serverUrl:'http://127.0.0.1:1'});
 await storage.writeJson(path.join(storage.cacheDirectory(process.env.LAF_TEST_PROFILE,'http://127.0.0.1:1'),'records.json'),{items:[{id:900,title:'蓝色保温杯',description:'教学楼二层拾获，请到值班室核对领取。',floor:'二层',status:'found',created_at:'2026-10-07 00:00:00',image_id:'11111111-1111-1111-1111-111111111111'},{id:901,title:'快速切换记录',description:'第二条详情',floor:'一层',status:'found',created_at:'2026-10-07 00:00:00',image_id:null}],syncedAt:new Date().toISOString()});
 await storage.writeJson(path.join(storage.cacheDirectory(process.env.LAF_TEST_PROFILE,'http://127.0.0.1:1'),'images','11111111-1111-1111-1111-111111111111.json'),{size:68,dataUrl:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII='});
 await app.whenReady();
 await storage.writeJson(path.join(process.env.LAF_TEST_PROFILE,'devices',createHash('sha256').update('http://127.0.0.1:1').digest('hex')+'.json'),{id:'11111111-1111-1111-1111-111111111111',encryptedToken:safeStorage.encryptString('a'.repeat(64)).toString('base64'),status:'approved',account_enabled:1,group_enabled:1,display_name:'设置测试设备'});
 require(path.resolve(__dirname,'../../laf-viewer/src/main.cjs'));
 await app.whenReady();await waitFor(()=>BrowserWindow.getAllWindows().length===1);
 const win=BrowserWindow.getAllWindows()[0],js=code=>win.webContents.executeJavaScript(code);
 await waitFor(()=>js('Boolean(document.querySelector("#storage-open"))'));
 assert.equal(await js('document.querySelectorAll(".resize-handle").length'),8);
 assert.equal(win.isAlwaysOnTop(),false);
 const initialBounds=win.getBounds();
 win.showInactive();await delay(300);
 const mouse=(type,offset)=>win.webContents.sendInputEvent({type,x:initialBounds.width-offset,y:initialBounds.height-offset,globalX:initialBounds.x+initialBounds.width-offset,globalY:initialBounds.y+initialBounds.height-offset,button:'left',clickCount:1});
 mouse('mouseDown',3);await delay(100);mouse('mouseMove',63);await delay(100);mouse('mouseUp',63);await delay(300);
 await waitFor(()=>Promise.resolve(win.getBounds().height<initialBounds.height));
 assert.ok(win.getBounds().width<initialBounds.width);
 await waitFor(async()=>{const value=await js('window.laf.settings()');return value.windowWidth===win.getBounds().width&&value.windowHeight===win.getBounds().height;});
 assert.equal(await js('document.documentElement.scrollWidth <= innerWidth'),true);
 // Restore a larger viewport for the remaining settings and screenshot assertions.
 const bounds=win.getBounds();
 await js(`window.laf.resizeWindow({phase:'start',edge:'se',x:0,y:0})`);
 await js(`window.laf.resizeWindow({phase:'move',x:${520-bounds.width},y:${760-bounds.height}})`);
 await js("window.laf.resizeWindow({phase:'end'})");
 assert.equal(win.getBounds().width,520);assert.equal(win.getBounds().height,760);
 assert.equal(await js('document.querySelector("#storage-open").textContent'),'设置');
 await js('document.querySelector("#storage-open").click()');
 await waitFor(()=>js('document.querySelector("dialog").open && Boolean(document.querySelector("#cacheDirectory"))'));
 assert.equal(await js('document.querySelector("#cacheDirectory").readOnly'),false);
 assert.equal(await js('document.querySelector(".device-settings").open'),false);
 assert.equal(await js('Boolean(document.querySelector("#settings-form").compareDocumentPosition(document.querySelector(".device-settings")) & Node.DOCUMENT_POSITION_FOLLOWING)'),true);
 assert.equal(await js('document.querySelector("#windowPlacement").value'),'desktop');
 assert.ok(await js('document.querySelector(".current-directory").textContent.includes("records.json")'));
 const chosen=path.join(output,'chosen-records');await fs.mkdir(chosen,{recursive:true});
 dialog.showOpenDialog=async()=>({canceled:false,filePaths:[chosen]});
 await js('document.querySelector("#choose-directory").click()');
 await waitFor(()=>js(`document.querySelector('#cacheDirectory').value===${JSON.stringify(chosen)}`));
 await delay(300);await fs.writeFile(path.join(output,'choose-location.png'),(await win.capturePage()).toPNG());
 await js('document.querySelector("#settings-form").requestSubmit()');
 await waitFor(()=>js('!document.querySelector("dialog").open'));
 assert.equal((await js('window.laf.settings()')).cacheDirectory,chosen);
 await waitFor(()=>js(`document.querySelector('#storage-path').textContent.includes(${JSON.stringify(chosen)})`));
 await js('document.querySelector("#storage-open").click()');await waitFor(()=>js('document.querySelector("dialog").open && Boolean(document.querySelector("#cacheDirectory"))'));
 const pasted=path.join(output,'pasted-records');
 await js(`document.querySelector('#cacheDirectory').value=${JSON.stringify(pasted)}; document.querySelector('#settings-form').requestSubmit()`);
 await waitFor(()=>js('!document.querySelector("dialog").open'));
 assert.equal((await js('window.laf.settings()')).cacheDirectory,pasted);
 assert.ok((await fs.stat(storage.cacheDirectory(pasted,'http://127.0.0.1:1'))).isDirectory());
 await js('document.querySelector("#storage-open").click()');await waitFor(()=>js('document.querySelector("dialog").open && Boolean(document.querySelector("#theme"))'));
 await js('document.querySelector("#theme").value="dark"; document.querySelector("#theme").dispatchEvent(new Event("change")); document.querySelector("#transparency").value=60; document.querySelector("#transparency").dispatchEvent(new Event("input"))');
 assert.equal(await js('document.documentElement.dataset.theme'),'dark');
 assert.equal(await js('document.documentElement.style.getPropertyValue("--panel-alpha")'),'0.4');
 assert.equal(await js('getComputedStyle(document.querySelector(".widget")).backgroundColor'),'rgba(17, 19, 24, 0.4)');
 await js('document.querySelector("#modal-close").click()');await delay(100);
 assert.equal(await js('document.documentElement.dataset.theme'),'light');
 assert.equal((await js('window.laf.settings()')).transparency,22);
 await js('document.querySelector("#storage-open").click()');await waitFor(()=>js('document.querySelector("dialog").open && Boolean(document.querySelector("#theme"))'));
 await js('document.querySelector("#theme").value="dark"; document.querySelector("#theme").dispatchEvent(new Event("change")); document.querySelector("#transparency").value=35; document.querySelector("#transparency").dispatchEvent(new Event("input"))');
 await delay(300);await fs.writeFile(path.join(output,'dark-settings.png'),(await win.capturePage()).toPNG());
 await js('document.querySelector("#settings-form").requestSubmit()');await waitFor(()=>js('!document.querySelector("dialog").open'));
 assert.equal((await js('window.laf.settings()')).theme,'dark');assert.equal((await js('window.laf.settings()')).transparency,35);
 const saved=await storage.readJson(path.join(process.env.LAF_TEST_PROFILE,'settings.json'));assert.equal(saved.theme,'dark');assert.equal(saved.transparency,35);
 await waitFor(()=>js('Boolean(document.querySelector("[data-id]"))'));
 const area=screen.getDisplayMatching(win.getBounds()).workArea;win.setBounds({x:area.x+Math.round((area.width-win.getBounds().width)/2),y:area.y+10});await delay(100);
 const fixedBounds=win.getBounds();let mainResizes=0;win.on('resize',()=>mainResizes++);
 await js('window.savedRecord=document.querySelector("[data-id]");document.querySelector("[data-id]").click()');
 await waitFor(()=>Promise.resolve(BrowserWindow.getAllWindows().some(window=>window!==win&&window.getTitle()==='失物详情')));
 const side=BrowserWindow.getAllWindows().find(window=>window!==win&&window.getTitle()==='失物详情'),sideJS=code=>side.webContents.executeJavaScript(code);
 await waitFor(()=>Promise.resolve(side.isVisible()));await waitFor(()=>sideJS('document.querySelector("#details").classList.contains("visible")'));assert.deepEqual(win.getBounds(),fixedBounds);assert.equal(mainResizes,0);assert.equal(await js('getComputedStyle(document.querySelector("h1")).fontSize'),'17px');assert.equal(await js('window.savedRecord===document.querySelector("[data-id]")'),true);
 assert.equal(await sideJS('document.documentElement.dataset.theme'),'dark');assert.ok(await sideJS('document.querySelector("h2").textContent.includes("蓝色保温杯")'));assert.equal(await sideJS('typeof window.lafDetail.saveSettings'),'undefined');await waitFor(()=>sideJS('Boolean(document.querySelector(".photo")?.complete)'));assert.equal(await js('document.querySelectorAll("#cards img").length'),0);
 await waitFor(()=>sideJS('getComputedStyle(document.querySelector("#details")).opacity==="1"'));
 const showSide=side.showInactive.bind(side);let repeatedShows=0;side.showInactive=(...args)=>{repeatedShows++;return showSide(...args);};
 await sideJS('window.opacityFrames=[];window.sampleOpacity=true;window.sawCrossfade=false;window.fixedHeader=document.querySelector(".detail-head");const tick=()=>{const pane=document.querySelector("#details"),layers=[...document.querySelectorAll(".content-layer")];window.opacityFrames.push({opacity:getComputedStyle(pane).opacity,background:getComputedStyle(pane).backgroundColor});if(layers.length===2&&layers.some(layer=>layer.getAnimations().length))window.sawCrossfade=true;if(window.sampleOpacity)requestAnimationFrame(tick)};tick()');
 await js(`document.querySelector('[data-id="901"]').click()`);await waitFor(()=>sideJS('document.querySelector("h2")?.textContent==="快速切换记录"'));assert.equal(await sideJS('window.sawCrossfade'),true);
 const viewerStorage=require('../../laf-viewer/src/storage.cjs'),originalImage=viewerStorage.imageData;viewerStorage.imageData=async(...args)=>{await delay(450);return originalImage(...args);};
 try{await js(`document.querySelector('[data-id="900"]').click()`);await delay(150);assert.equal(await sideJS('document.querySelector("h2").textContent'),'快速切换记录');assert.equal(await sideJS('getComputedStyle(document.querySelector("#details")).opacity'),'1');await js(`document.querySelector('[data-id="901"]').click()`);await delay(650);assert.equal(await sideJS('document.querySelector("h2").textContent'),'快速切换记录');assert.equal(await sideJS(`document.querySelectorAll('[data-record-id="900"]').length`),0);}finally{viewerStorage.imageData=originalImage;}
 await js(`document.querySelector('[data-id="900"]').click()`);await waitFor(()=>sideJS('document.querySelector("h2")?.textContent==="蓝色保温杯"'));await waitFor(()=>sideJS('document.querySelector(".photo")?.naturalWidth>0'));await sideJS('window.sampleOpacity=false');const frames=await sideJS('window.opacityFrames');assert.ok(frames.length>10&&frames.every(frame=>frame.opacity==='1'));assert.equal(new Set(frames.map(frame=>frame.background)).size,1);assert.equal(await sideJS('window.fixedHeader===document.querySelector(".detail-head")'),true);assert.equal(repeatedShows,0);side.showInactive=showSide;
 assert.equal(BrowserWindow.getAllWindows().filter(window=>window.getTitle()==="失物详情").length,1);assert.deepEqual(win.getBounds(),fixedBounds);
 await sideJS('window.lafDetail.width(460)');assert.equal((await js('window.laf.settings()')).detailWidth,460);assert.deepEqual(win.getBounds(),fixedBounds);assert.equal(mainResizes,0);
 await fs.writeFile(path.join(output,'side-detail.png'),(await side.capturePage()).toPNG());
 await sideJS('document.querySelector("#close").click()');await waitFor(()=>Promise.resolve(!side.isVisible()));assert.deepEqual(win.getBounds(),fixedBounds);assert.equal(await js('document.querySelector(".record.active")===null'),true);
 await js('document.querySelector("#storage-open").click()');await waitFor(()=>js('document.querySelector("dialog").open'));await js('document.querySelector("#detailSide").value="left";document.querySelector("#settings-form").requestSubmit()');await waitFor(()=>js('!document.querySelector("dialog").open'));
 // Position the main window to leave enough room for an explicitly left-aligned side window.
 win.setBounds({x:area.x+Math.min(area.width-win.getBounds().width,480)});await delay(100);const leftBounds=win.getBounds();const resizeBaseline=mainResizes;
 await js('document.querySelector("[data-id]").click()');await waitFor(()=>Promise.resolve(side.isVisible()));assert.ok(side.getBounds().x<win.getBounds().x);assert.deepEqual(win.getBounds(),leftBounds);
 const beforeMove=side.getBounds();win.setBounds({y:win.getBounds().y+20});await delay(100);assert.equal(side.getBounds().y,beforeMove.y+20);const movedBounds=win.getBounds();
 await sideJS('document.querySelector("#width-handle").dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowLeft",bubbles:true}))');await waitFor(async()=> (await js('window.laf.settings()')).detailWidth===480);assert.deepEqual(win.getBounds(),movedBounds);assert.equal(mainResizes,resizeBaseline);
 await js('document.querySelector("[data-id]").click()');await waitFor(()=>Promise.resolve(!side.isVisible()));assert.deepEqual(win.getBounds(),movedBounds);
 // Repeated open/close reuses the existing side window and never resizes the main window.
 for(let i=0;i<3;i++){await js('document.querySelector("[data-id]").click()');await waitFor(()=>Promise.resolve(side.isVisible()));await js('document.querySelector("[data-id]").click()');await waitFor(()=>Promise.resolve(!side.isVisible()));assert.deepEqual(win.getBounds(),movedBounds);}
 assert.equal(BrowserWindow.getAllWindows().filter(window=>window.getTitle()==='失物详情').length,1);
 await js('document.querySelector("#storage-open").click()');await waitFor(()=>js('document.querySelector("dialog").open'));
 await js('document.querySelector("#windowPlacement").value="top";document.querySelector("#settings-form").requestSubmit()');await waitFor(()=>js('!document.querySelector("dialog").open'));assert.equal(win.isAlwaysOnTop(),true);
 await js('document.querySelector("#storage-open").click()');await waitFor(()=>js('document.querySelector("dialog").open'));await js('document.querySelector("#windowPlacement").value="desktop";document.querySelector("#settings-form").requestSubmit()');await waitFor(()=>js('!document.querySelector("dialog").open'));assert.equal(win.isAlwaysOnTop(),false);
 if(process.platform==='win32'){
  const cover=new BrowserWindow({width:400,height:300,show:false});cover.show();cover.focus();await delay(1500);
  const handle=w=>{const b=w.getNativeWindowHandle();return b.length===8?b.readBigUInt64LE().toString():String(b.readUInt32LE());};
  const probe=`Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public static class LafZProbe{[DllImport("user32.dll")]public static extern IntPtr GetWindow(IntPtr h,uint command);}'; $probeHandle=[IntPtr]([long]${handle(cover)});$widgetHandle=[IntPtr]([long]${handle(win)});$isBelow=$false;for($i=0;$i -lt 1000;$i++){$probeHandle=[LafZProbe]::GetWindow($probeHandle,2);if($probeHandle -eq [IntPtr]::Zero){break};if($probeHandle -eq $widgetHandle){$isBelow=$true;break}};if(-not $isBelow){throw 'Desktop widget should be below the covering window'};Write-Output 'native-layer-ok'`;
  const result=require('node:child_process').execFileSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',probe],{windowsHide:true,encoding:'utf8'});assert.ok(result.includes('native-layer-ok'));cover.destroy();
 }
 await js('window.laf.settings().then(value=>window.laf.saveSettings({...value,windowPlacement:"top",alwaysOnTop:true}))');await delay(200);win.show();win.focus();await delay(300);await js('window.mouseLog=[];for(const type of ["pointerdown","click","dblclick"])document.addEventListener(type,event=>window.mouseLog.push({type,target:event.target.id,x:event.clientX,y:event.clientY}),true)');const titlePoint=await js('(()=>{const r=document.querySelector("#reader-open").getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()');const widgetBounds=win.getBounds(),physicalPoint=screen.dipToScreenPoint({x:Math.round(widgetBounds.x+titlePoint.x),y:Math.round(widgetBounds.y+titlePoint.y)});
 const nativeMouse=`Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public static class LafMouseProbe{[StructLayout(LayoutKind.Sequential)]public struct Point{public int x,y;}[DllImport("user32.dll")]public static extern IntPtr SetThreadDpiAwarenessContext(IntPtr c);[DllImport("user32.dll")]public static extern bool GetCursorPos(out Point p);[DllImport("user32.dll")]public static extern bool SetCursorPos(int x,int y);[DllImport("user32.dll")]public static extern void mouse_event(uint f,uint x,uint y,uint data,UIntPtr extra);[DllImport("user32.dll")]public static extern IntPtr WindowFromPoint(Point p);public static void DoubleClick(int x,int y){SetThreadDpiAwarenessContext(new IntPtr(-4));Point saved;GetCursorPos(out saved);try{SetCursorPos(x,y);for(int i=0;i<2;i++){mouse_event(2,0,0,0,UIntPtr.Zero);mouse_event(4,0,0,0,UIntPtr.Zero);System.Threading.Thread.Sleep(70);}}finally{SetCursorPos(saved.x,saved.y);}}}';[LafMouseProbe]::DoubleClick(${physicalPoint.x},${physicalPoint.y})`;
 await new Promise((resolve,reject)=>require('node:child_process').execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command',nativeMouse],{windowsHide:true},error=>error?reject(error):resolve()));await delay(200);assert.ok((await js('window.mouseLog')).some(event=>event.type==='dblclick'&&event.target==='reader-open'));win.setAlwaysOnTop(false);await waitFor(()=>Promise.resolve(BrowserWindow.getAllWindows().length===3));
 const reader=BrowserWindow.getAllWindows().find(window=>window!==win&&window!==side),readerJS=code=>reader.webContents.executeJavaScript(code);await waitFor(()=>readerJS('Boolean(document.querySelector("[data-id]"))'));assert.equal(await readerJS('typeof window.laf.saveSettings'),'undefined');await readerJS('document.querySelector("[data-id]").click()');await waitFor(()=>readerJS('document.querySelector("#detail").textContent.includes("蓝色保温杯")'));
 await js('document.querySelector("#reader-open").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))');await delay(200);assert.equal(BrowserWindow.getAllWindows().length,3);reader.destroy();
 await js('document.querySelector("#storage-open").click()');await waitFor(()=>js('document.querySelector("dialog").open'));await js('document.querySelector("input[name=experimentalReaderWindow]").checked=false;document.querySelector("#settings-form").requestSubmit()');await waitFor(()=>js('!document.querySelector("dialog").open'));await js('document.querySelector("#reader-open").dispatchEvent(new MouseEvent("dblclick",{bubbles:true}))');await delay(300);assert.equal(BrowserWindow.getAllWindows().length,2);
 await js('document.querySelector("[data-id]").click()');await waitFor(()=>Promise.resolve(side.isVisible()));const identityFile=path.join(process.env.LAF_TEST_PROFILE,'devices',createHash('sha256').update('http://127.0.0.1:1').digest('hex')+'.json');const identity=await storage.readJson(identityFile);await storage.writeJson(identityFile,{...identity,status:'revoked'});assert.deepEqual((await js('window.laf.records(false)')).items,[]);await waitFor(()=>Promise.resolve(!side.isVisible()));assert.ok(await js('window.laf.openDetail(900).then(result=>result===false).catch(()=>true)'));
 await fs.writeFile(path.join(output,'result.json'),JSON.stringify({success:true,checks:['visible-storage-button','display-real-file-location','browse-folder','paste-path','persist-location','display-current-location']},null,2));
 console.log('只读 GUI 验证通过：系统鼠标双击标题打开独立窗口、边角缩放、独立侧窗、背景恒定、正文交叉淡化、缓存图片预解码、延迟与过期请求、主窗尺寸不变、左右跟随、详情宽度持久化、目录选择、主题和透明度');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{app.emit('before-quit');app.exit(process.exitCode||0);});
